name: cal_time_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  awesome_notifications: ^0.9.2
  device_calendar: ^4.3.2
  dynamic_color: ^1.7.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  iconly: ^1.0.1
  provider: "^5.0.0"
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/time.png
